### ISSUE TITLE
Detailed plot of anomalies

### ISSUE THREAD

**Issue by fredmontet** [fredmontet/ontime#22]
## Objective

The aim of this task is to make it easy to plot time series anomalies. For that, a method is proposed to plot point, continuous and contextual anomalies given a few BinaryTimeSeries.

## Description

A method like `plot_anomalies(point_anomalies_bts, contextual_anomalies_bts, collective_anomalies_bts, ...)` should be developed. Maybe, a new object like `AnomalyTimeSeries` should be created so that the method signature can become `plot_anomalies(anomaly_ts)`.

In this plot, the different types of anomalies can be visualised independently of each other in a visually appealing way. 

## Tasks

- [x] AnomalyTimeSeries has been discussed and eventually implemented
- [x] Point anomalies is added to the plot
- [x] Contextual anomalies is added to the plot
- [x] Collective anomalies is added to the plot
- [ ] Seasonal anomalies is added to the plot
- [ ] Cyclical anomalies is added to the plot

### Point anomalies

A point anomaly is a single data point that is significantly different from the rest of the data. It can be caused by measurement errors, system malfunctions, or other factors.

![Screenshot 2023-11-16 at 09 26 14](https://github.com/fredmontet/ontime/assets/4543916/c2225b46-b1fb-4ac9-b695-8da6af1bdba4)

### Contextual anomalies

Contextual anomalies are data points that are not unusual on their own, but become anomalous in a particular context. For example, a sudden spike in website traffic on a holiday is not unusual, but a similar spike on a regular weekday could be an anomaly.

![Screenshot 2023-11-16 at 09 26 31](https://github.com/fredmontet/ontime/assets/4543916/832347b3-17f4-40b6-942c-6860d9152bc6)

### Collective anomalies

Collective anomalies are groups of data points that are anomalous when considered together. They can be caused by changes in the underlying system or by external factors affecting the system.

![Screenshot 2023-11-16 at 09 27 14](https://github.com/fredmontet/ontime/assets/4543916/8ef1d0e0-eb14-4190-b321-1d79c1f3f3a7)

### Seasonal anomalies

Seasonal anomalies occur when the time series data show regular patterns or cycles, but a particular cycle deviates significantly from the expected pattern. For example, unusually high sales during a non-peak season would be a seasonal anomaly.

### Cyclical anomalies

Cyclical anomalies occur when the time series data shows long-term cycles or trends that deviate significantly from the expected pattern. These anomalies are often caused by external factors such as economic recessions or natural disasters.
